const w = 52
const h = 60

export default {
  right: {
    sit: [
      { x: 0 * w, y: 0 * h, w , h }
    ],
    chair: [
      { x: 6 * w, y: 1 * h, w , h }
    ],
    sitIdle: [
      { x: 1 * w, y: 0 * h, w , h }
    ],
    sitAngry: [
      { x: 2 * w, y: 0 * h, w , h }
    ],
    sitFurious: [
      { x: 3 * w, y: 0 * h, w , h }
    ],
    expand: [
      { x: 2 * w, y: 0 * h, w , h },
      { x: 2 * w, y: 0 * h, w , h },
      { x: 2 * w, y: 0 * h, w , h },
      { x: 2 * w, y: 0 * h, w , h },
      { x: 2 * w, y: 0 * h, w , h },
      { x: 3 * w, y: 0 * h, w , h },
      { x: 3 * w, y: 0 * h, w , h },
      { x: 3 * w, y: 0 * h, w , h },
      { x: 3 * w, y: 0 * h, w , h },
      { x: 3 * w, y: 0 * h, w , h },
      { x: 4 * w, y: 0 * h, w , h },
      { x: 5 * w, y: 0 * h, w , h },
      { x: 4 * w, y: 0 * h, w , h },
      { x: 5 * w, y: 0 * h, w , h },
      { x: 4 * w, y: 0 * h, w , h },
      { x: 5 * w, y: 0 * h, w , h },
      { x: 4 * w, y: 0 * h, w , h },
      { x: 5 * w, y: 0 * h, w , h },
      { x: 4 * w, y: 0 * h, w , h },
      { x: 5 * w, y: 0 * h, w , h },
      { x: 4 * w, y: 0 * h, w , h },
      { x: 5 * w, y: 0 * h, w , h },
      { x: 6 * w, y: 0 * h, w , h },
      { x: 7 * w, y: 0 * h, w , h },
      { x: 7 * w, y: 0 * h, w , h },
      { x: 7 * w, y: 0 * h, w , h },
      { x: 7 * w, y: 0 * h, w , h },
      { x: 7 * w, y: 0 * h, w , h },
      { x: 7 * w, y: 0 * h, w , h },
      { x: 7 * w, y: 0 * h, w , h },
    ],
    standup: [
      { x: 0 * w, y: 1 * h, w , h },
      { x: 1 * w, y: 1 * h, w , h },
      { x: 2 * w, y: 1 * h, w , h },
      { x: 3 * w, y: 1 * h, w , h },
      { x: 4 * w, y: 1 * h, w , h },
      { x: 5 * w, y: 1 * h, w , h }
    ],
    idle: [
      { x: 0 * w, y: 2 * h, w , h: h -1 },
      { x: 1 * w, y: 2 * h, w , h: h -1 },
      { x: 2 * w, y: 2 * h, w , h: h -1 },
      { x: 3 * w, y: 2 * h, w , h: h -1 },
      { x: 2 * w, y: 2 * h, w , h: h -1 },
      { x: 1 * w, y: 2 * h, w , h: h -1 },
    ],
    happy: [
      { x: 4 * w, y: 2 * h, w , h },
    ],
    move: [
      { x: 0 * w, y: 3 * h, w , h: h - 1 },
      { x: 0 * w, y: 3 * h, w , h: h - 1 },
      { x: 1 * w, y: 3 * h, w , h: h - 1 },
      { x: 1 * w, y: 3 * h, w , h: h - 1 },
      { x: 2 * w, y: 3 * h, w , h: h - 1 },
      { x: 2 * w, y: 3 * h, w , h: h - 1 },
      { x: 3 * w, y: 3 * h, w , h: h - 1 },
      { x: 3 * w, y: 3 * h, w , h: h - 1 },
      { x: 4 * w, y: 3 * h, w , h: h - 1 },
      { x: 4 * w, y: 3 * h, w , h: h - 1 },
    ],
    run: [
      { x: 0 * w, y: 4 * h, w , h },
      { x: 1 * w, y: 4 * h, w , h },
      { x: 2 * w, y: 4 * h, w , h },
      { x: 3 * w, y: 4 * h, w , h },
      { x: 4 * w, y: 4 * h, w , h },
    ],
    attack: [
      { x: 0 * w, y: 5 * h, w , h },
      { x: 0 * w, y: 5 * h, w , h },
      { x: 0 * w, y: 5 * h, w , h },
      { x: 0 * w, y: 5 * h, w , h },
      { x: 1 * w, y: 5 * h, w , h },
      { x: 1 * w, y: 5 * h, w , h },
      { x: 1 * w, y: 5 * h, w , h },
      { x: 1 * w, y: 5 * h, w , h },
      { x: 2 * w, y: 5 * h, w , h },
      { x: 2 * w, y: 5 * h, w , h },
      { x: 2 * w, y: 5 * h, w , h },
      { x: 2 * w, y: 5 * h, w , h },
      { x: 2 * w, y: 5 * h, w , h },
      { x: 2 * w, y: 5 * h, w , h },
      { x: 2 * w, y: 5 * h, w , h },
      { x: 3 * w, y: 5 * h, w , h },
      { x: 4 * w, y: 5 * h, w , h },
      { x: 5 * w, y: 5 * h, w , h },
      { x: 6 * w, y: 5 * h, w , h },
      { x: 7 * w, y: 5 * h, w , h },
      { x: 8 * w, y: 5 * h, w , h },
      { x: 8 * w, y: 5 * h, w , h },
      { x: 8 * w, y: 5 * h, w , h },
      { x: 8 * w, y: 5 * h, w , h },
      { x: 8 * w, y: 5 * h, w , h },
      { x: 8 * w, y: 5 * h, w , h },
    ],
  },
  left: {
    sit: [
      { x: (9 + 0) * w, y: 0 * h, w , h }
    ],
    expand: [
      { x: (9 + 1) * w, y: 0 * h, w , h },
      { x: (9 + 1) * w, y: 0 * h, w , h },
      { x: (9 + 1) * w, y: 0 * h, w , h },
      { x: (9 + 1) * w, y: 0 * h, w , h },
      { x: (9 + 1) * w, y: 0 * h, w , h },
      { x: (9 + 2) * w, y: 0 * h, w , h },
      { x: (9 + 2) * w, y: 0 * h, w , h },
      { x: (9 + 2) * w, y: 0 * h, w , h },
      { x: (9 + 2) * w, y: 0 * h, w , h },
      { x: (9 + 2) * w, y: 0 * h, w , h },
      { x: (9 + 3) * w, y: 0 * h, w , h },
      { x: (9 + 4) * w, y: 0 * h, w , h },
      { x: (9 + 3) * w, y: 0 * h, w , h },
      { x: (9 + 4) * w, y: 0 * h, w , h },
      { x: (9 + 3) * w, y: 0 * h, w , h },
      { x: (9 + 4) * w, y: 0 * h, w , h },
      { x: (9 + 3) * w, y: 0 * h, w , h },
      { x: (9 + 4) * w, y: 0 * h, w , h },
      { x: (9 + 3) * w, y: 0 * h, w , h },
      { x: (9 + 4) * w, y: 0 * h, w , h },
      { x: (9 + 3) * w, y: 0 * h, w , h },
      { x: (9 + 4) * w, y: 0 * h, w , h },
      { x: (9 + 5) * w, y: 0 * h, w , h },
      { x: (9 + 6) * w, y: 0 * h, w , h },
      { x: (9 + 6) * w, y: 0 * h, w , h },
      { x: (9 + 6) * w, y: 0 * h, w , h },
      { x: (9 + 6) * w, y: 0 * h, w , h },
      { x: (9 + 6) * w, y: 0 * h, w , h },
      { x: (9 + 6) * w, y: 0 * h, w , h },
      { x: (9 + 6) * w, y: 0 * h, w , h },
    ],
    standup: [
      { x: (9 + 0) * w, y: 1 * h, w , h },
      { x: (9 + 1) * w, y: 1 * h, w , h },
      { x: (9 + 2) * w, y: 1 * h, w , h },
      { x: (9 + 3) * w, y: 1 * h, w , h },
      { x: (9 + 4) * w, y: 1 * h, w , h },
      { x: (9 + 5) * w, y: 1 * h, w , h }
    ],
    idle: [
      { x: (9 + 0) * w, y: 2 * h, w , h: h - 1 },
      { x: (9 + 1) * w, y: 2 * h, w , h: h - 1 },
      { x: (9 + 2) * w, y: 2 * h, w , h: h - 1 },
      { x: (9 + 3) * w, y: 2 * h, w , h: h - 1 },
      { x: (9 + 2) * w, y: 2 * h, w , h: h - 1 },
      { x: (9 + 1) * w, y: 2 * h, w , h: h - 1 },
    ],
    happy: [
      { x: (9 + 4) * w, y: 2 * h, w , h },
    ],
    move: [
      { x: (9 + 0) * w, y: 3 * h, w , h: h -1 },
      { x: (9 + 0) * w, y: 3 * h, w , h: h -1 },
      { x: (9 + 1) * w, y: 3 * h, w , h: h -1 },
      { x: (9 + 1) * w, y: 3 * h, w , h: h -1 },
      { x: (9 + 2) * w, y: 3 * h, w , h: h -1 },
      { x: (9 + 2) * w, y: 3 * h, w , h: h -1 },
      { x: (9 + 3) * w, y: 3 * h, w , h: h -1 },
      { x: (9 + 3) * w, y: 3 * h, w , h: h -1 },
      { x: (9 + 4) * w, y: 3 * h, w , h: h -1 },
      { x: (9 + 4) * w, y: 3 * h, w , h: h -1 },
    ],
    run: [
      { x: (9 + 0) * w, y: 4 * h, w , h },
      { x: (9 + 1) * w, y: 4 * h, w , h },
      { x: (9 + 2) * w, y: 4 * h, w , h },
      { x: (9 + 3) * w, y: 4 * h, w , h },
      { x: (9 + 4) * w, y: 4 * h, w , h },
    ],
    attack: [
      { x: (9 + 0) * w, y: 5 * h, w , h },
      { x: (9 + 0) * w, y: 5 * h, w , h },
      { x: (9 + 0) * w, y: 5 * h, w , h },
      { x: (9 + 0) * w, y: 5 * h, w , h },
      { x: (9 + 1) * w, y: 5 * h, w , h },
      { x: (9 + 1) * w, y: 5 * h, w , h },
      { x: (9 + 1) * w, y: 5 * h, w , h },
      { x: (9 + 1) * w, y: 5 * h, w , h },
      { x: (9 + 2) * w, y: 5 * h, w , h },
      { x: (9 + 2) * w, y: 5 * h, w , h },
      { x: (9 + 2) * w, y: 5 * h, w , h },
      { x: (9 + 2) * w, y: 5 * h, w , h },
      { x: (9 + 2) * w, y: 5 * h, w , h },
      { x: (9 + 2) * w, y: 5 * h, w , h },
      { x: (9 + 2) * w, y: 5 * h, w , h },
      { x: (9 + 3) * w, y: 5 * h, w , h },
      { x: (9 + 4) * w, y: 5 * h, w , h },
      { x: (9 + 5) * w, y: 5 * h, w , h },
      { x: (9 + 6) * w, y: 5 * h, w , h },
      { x: (9 + 7) * w, y: 5 * h, w , h },
      { x: (9 + 8) * w, y: 5 * h, w , h },
      { x: (9 + 8) * w, y: 5 * h, w , h },
      { x: (9 + 8) * w, y: 5 * h, w , h },
      { x: (9 + 8) * w, y: 5 * h, w , h },
      { x: (9 + 8) * w, y: 5 * h, w , h },
      { x: (9 + 8) * w, y: 5 * h, w , h },
    ],
  }
}